---
- hosts: master0 #the leader
  vars:
    service_name: docker-ui
  tasks:
    - name: Get services
      shell: docker service ls
      register: services
      tags:
        - docker-ui

    - name: Start docker UI service
      shell: docker service create
          --name {{service_name}}
          --publish 3000:9000
          --constraint 'node.role == manager'
          --mount type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock
          portainer/portainer -H unix:///var/run/docker.sock
      when: "services.stdout.find('{{service_name}}') == -1"
      tags:
        - docker-ui
        - service
